### ISSUE TITLE
Error in installing ivtmetrics

### ISSUE THREAD

**Issue by shinpaul14** [CAMMA-public/ivtmetrics#6]
I am having a problem installing the ivtmetrics. 

How can I solve this problem when trying "pip install ivtmetrics "?

In the terminal it returns this line . 

`Collecting ivtmetrics
  Using cached ivtmetrics-0.1.2.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\paul\AppData\Local\Temp\pip-install-_dgtxbqu\ivtmetrics_e2a2cc4797e2453ea4ae549c0b8a38f3\setup.py", line 5, in <module>
          long_description = (this_directory / "README.rst").read_text()
        File "C:\Users\paul\anaconda3\envs\sdswin\lib\pathlib.py", line 1179, in read_text 
          return f.read()
        File "C:\Users\paul\anaconda3\envs\sdswin\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6222: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.     
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.`

**Comment by Bhatijagdish** [comment]
@shinpaul14 The issue is here, you can also make the change locally: https://github.com/CAMMA-public/ivtmetrics/pull/7/files
